friends_f_chars <- c('rachel','monica','phoebe',
                     'adrienne','alexandra steele','alice','alison','amber','amy',
                     'andrea','angela','ashley','aunt iris','aunt lillian','aunt lisa','aunt millie',
                     'aurora','bernice','bitsy','bonnie','brenda','cailin','caitlin','carol',
                     'carol and susan','caroline','cassie','catherine','cecilia','celia',
                     'cheryl','chloe','claudia','colleen','cynthia','dana','danielle','dina',
                     'dream monica','elizabeth','elizabeth hornswoggle','emily','emma',
                     'erica','erin','estelle','estl','fake monica','fat monica',
                     'felicity','fergie','fran','frankie','frannie','gail','ginger',
                     'glenda','grandma tribbiani','heather','helen','helena','henrietta',
                     'hilda','hillary','isabella','jade','janice','jasmine','jeanette',
                     'jeannine','jen','jennifer','jessica ashley','jessica lockhart','jill',
                     'jo lynn','joanna','joanne','judy','julia','kara','karin','kate','kathy',
                     'katie','kiki','kim','kori','krista','kristen','kristin','laura',
                     'lauren','leslie','lisa','lizzie','lorraine','luisa','lydia','margha',
                     'marjorie','marsha','mary ellen','meg','megan','mel','melanie','melissa',
                     'mich','michelle','mindy','mischa','missy','mnca','molly','mona',
                     'monica and phoebe','monica and rachel',
                     "mrs buffay","mrs green","mrs. bing","mrs. burgin","mrs. burkart",
                     "mrs. chatracus","mrs. geller","mrs. green","mrs. greene","mrs. lynch",
                     "mrs. potter","mrs. tedlock","mrs. tribbiani","mrs. wallace",
                     "mrs. waltham","mrs. wineburg","ms. geller","ms. lambert","ms. mckenna",
                     'nancy','nina','phoe','phoebe ',
                     'phoebe and leslie','phoebe and monica','phoebe and rachel',
                     'phoebe sr','phoebe sr.','racel','rach','rache','rahcel',
                     'rachel and bonnie','rachel and monica','rachel and phoebe',
                     'rita','ronni','sally','sandy','sarah','shelley','sonia',
                     'sophie','stephanie','susan','susie','trudie styler','ursula',
                     'wendy','whitney','young monica','zoe'
                     )

seinfeld_f_chars <- c(
    'elaine','.elaine','benes','ealine','elaien','elaine ','elainelaine','eliane',
    'susan','suan and allsion',
    'abby','alicia','alison','allison','allsion','amy','angela','anna',
    'audrey','aunt may','ava','babs','barbara','becky','beth','betsy',
    'bette','bonnie','bridget','candice bergen','carol','carrie','celia',
    'charmaine','chelsea','cheryl','cindy','clare','coco','corinne',
    'dana','danielle','debby','deena','denise','diane','dolores','doris',
    'ellen','emily','estelle','estelle ','eva','evelyn','frankie','gail',
    'gennice','gina','girlfriend donna','gladys','glenda','gwen','heather','helen',
    'helena','helene','hilde','holly','ilene','isabel','izzy','izzy and izzy jr',
    'izzy jr.','izzy sr.','jackie','jane','janet','janice','jeanine','jeannie',
    'jenna','jenny','jessie','joan','joanne','jodi','joyce','judy','julianna',
    'julie','karen','karin','kathy lee ','katie','katy','katya','kelly','kelly the waitress',
    'keri','kim','kristin','lanette','laura','lena','leslie','lindsay','lisa','lisi',
    'liz','lois','loretta','lorraine','louise','mabel','marcy','margaret','marla','marian',
    'marisa','marla','marlene','mary anne','maryedith','maura','melissa','meryl',
    'miranda','misha','mollika','molly','mona','monica',
    "mrs allister","mrs hamilton","mrs reichman","mrs. c","mrs. choate","mrs. enright",
    "mrs. o","mrs. payton","mrs. peterman","mrs. ross","mrs. s","mrs. sanger",
    "mrs. sokol","mrs. zanfino","mrs.arm","ms. baines","ms. de granmont","ms. jordan",
    'mulva','nana','nancy','naomi','nikki','nina','noreen','olive','pam','pamela',
    'patrice','patti','patty','paula','peggy','rachel','rachel ','raquel','rebecca',
    'rhisa','rita','roberta','rochelle','roxanne','ruby','rula','ruthie',
    'sally','sandi','sandra','sandy','sara','sharon','sheila','sheila ','shelley','shelly',
    'sidra','siena','sister roberta','sophie','stacey','stefanie','stella',
    'susie','sylvia','tara','tia','tina','tina ','tv elaine','valerie','vanessa',
    'victoria','vivian','wendy','winona'
)

scrubs_f_chars <- c(
    'carla','carla and elliot','elliot','jordan','laverne','dr. reid',
    'alex','allison','betty','carnie','carol','charice','claire',
    'daisy','danni','denise','dina','elaine','enid','fantasy mrs. cantwell',
    'gaby','glenda','gloria','helen','jackie','jamie','janice','jennifer','jenny',
    'jill','julie','karen','kelly','kim','kristen','kylie','lauren',
    'leslie','lindsay','lisa','maddie','maggie','maureen mccormick','meredith',
    'miss myers','molly',
    "mrs. bell","mrs. blitt","mrs. brown","mrs. bumbry","mrs. carter","mrs. chang",                                                                            
    "mrs. cooke","mrs. covello","mrs. donnelly","mrs. farr","mrs. gorski",
    "mrs. guerrero","mrs. kay","mrs. kellerman","mrs. larkin","mrs. maccalla",                                                                         
    "mrs. peele","mrs. pratt","mrs. reid","mrs. stanley","mrs. tanner",                                                                           
    "mrs. tracy","mrs. turk","mrs. warner","mrs. watson","mrs. wilk","ms. turk",
    'nancy','neena','noelle','paige','patricia','rebecca','rosanna','sally',
    'samantha','sheila','sister carla','tammy','tracy','wendy','whitney',
    'wonder molly','young elliot',
    'dr. donna','dr. gerson','dr. kim','dr. miller','dr. lemmon',
    'nurse kearney','nurse roberts','nurse tisdale'
)

frasier_f_chars <- c(
    'daphne','roz',
    'charlotte','ronee','lilith','bebe','gertrude','mel',
    'abby','adelle','alice','allison','amanda','amber','andi','angela','ann',
    'anne','annie','antonia','arleen','audrey','babette','becky','bernice',
    'beth','bethany','betsy','betty','beverly','bobbie','bonnie','brandy',
    'brenda','bridgett','britney','caitlin','carla','carol','caroline',
    'carrie','cassandra','catherine','cathy','cecilia','celeste','chelsea',
    'cheryl','christina','christine','cindy','claire','clare','clarice','claudia',
    'colette','colleen','connie','cora','crystal','cynthia','dana','danielle',
    'darla','deirdre','denise','diane','dinah','donna','dorathea','doris',
    'dorothy','dorothy parker','dorris','edna','eileen','elaine','elise',
    'elizabeth','ellie','emily','erin','estelle','eve','evelyn','faye',
    'felicity','florence','francesca','francine','frederika','gail',
    'gladys','glinka','gretchen','heather','helen','holly','jane','janelle',
    'janet','janice','jelly','jen','jennifer','jenny','jessica','jill',
    'joanna','joanne','jody','joselia','judy','julia','june','karen','kari','kate',
    'kathy','kelly','kim','kimberly','kristi','lacey','lana','laura','leslie',
    'lillian','linda','lisa','lisbeth','liz','lois','loretta','lorna','lorraine',
    'louise','lucy','lydia','madeline','maggie','margaret','margie','maria',
    'marianne','maria','marilyn','marjorie','marlene','martha','marvella','mary',
    'maryanne','maureen','maxine','melody','mia','mildred','mimi','mindy',
    'miranda','moira','molly','monica','nancy','nanette','natalie','nora',
    'pam','pamela','paris','paula','peg','peggy','penelope','phyllis','polly',
    'poppy','portia','rachel','rebecca','regan','renata','rita','rochelle',
    'sabrina','sally','sandy','sara briggs','shannon','sharon','sheila','sherry',
    'shirley','sophie','stephanie','susan','susanna','suzy','tiffany','tina',
    'tricia','trish','trudy','vanessa','vera','vickie','willa','yvette','yvonne','zora'
)

marriedwc_f_chars <- c(
    'kel','kelly','marcy','peg','peggy',
    'alexis','alexis and monique','amber','april','ariel','bebe','becky','belinda',
    'betsy','betty','brandi','carla','charli','cherise','chlsea','cindy','coco',
    'cortny','crystal','cyndy','debbie','delilah','denise','donna','elaine','elena',
    'enid','esther','esther i','euneta','fanny','fern','fifi','fran','frieda',
    'geena','ginger','gladys','gloria','grechn','greta','hariet','heidi','helga',
    'hethr','hilgar','inga','jade','jamie','janie','jeannie','jenifr','jill',
    'joanie','judy','julie','june','kara','kitty','lauren','leona','linda',
    'lisa','liz','lois','lola','louise','lucy','mandi','mandy','marie','marilyn',
    'marla','marsha','melba','melinda','mindy','miranda','miss p','missp',
    'molly','mona','monique','mopsy','mrnda','mrs. g','mrs. m','mrs. w','mrstot',
    'nancy','naomi','palina','pam','paula','paulina','peaches','renee',
    'rhonda','ricki','rita','roberta','rochelle e.','rochelle f. staten',
    'sally','samantha','sascha','sheila','sherry','sonya','stacey','starla',
    'susan','susie','sylvia','thelma','tina','topsy','vicki','vicky','wanda',
    'wendy','yvette','zelda'
)

wg_f_chars <- c(
    'grace','karen','rosario',
    'alice','april','beth','candice','angie','candy','charlotte','bernie',
    'bobbi','annette','barbra','bebe','bobbi adler','casey','cher',
    'annie','bonnie','carla','cheryl','claire','connie',
    'deirdre','eleanor','diane','eva','fannie','fiona','gabby','gillian',
    'debbie','dorleen','eileen','ellen','felicia','ginny','danielle',
    'deborah harry','elaine','grace and heidi','heidi','joanne','joyce',
    'judy','karen','grace on tv','helena','jamie','jodie','julie',
    'karen and candice','grace and karen','janet','jean','judith',
    'karen and candy','grace and grace','holly','hurumi','jennifer',
    'joan','judith mcfarland','karen and gillian','kim','lucilee',
    'margot','kimmy','lenore','liz','lucille','mariln','karen and karen',
    'katherine','lila','lois','lucy','maisie','marilyn','marta','michelle',
    'karen and liz','katie','kitty','marcy','karen and lorraine',
    'leni','letty','lorraine','lynette','margaret','marion','martina',
    'melanie','naomi','pam','mona','mrs. glasser','nicole','olivia',
    'pamela','peggy','rita','mrs. presman','nadine','patti','phyllis',
    'rhonda','mrs friedman','mrs. pressman','nana','mrs sanwald',
    'mrs. truman','nancy','polly','rose','sally','sandra','sarah',
    'sharon','sissy','sister robert','val','winnie','roz',
    'ruby','sheila','sister louise','stephanie','sue','sylvia',
    'tina','val and grace','vicky','zandra'
)

office_f_chars <- c(
    'pam','erin','angela','meredith','phyllis','kelly','karen','anglea','phylis','phyliss','pam ',
    'jan','holly','nellie','nellie bertram',
    'angela and kelly','aunt shirley','carla fern','astrid','carol','cathy','alice','amy',
    'carol stills','cece','chelsea','carrol','abby','barbara','beth','cindy','brenda',
    'carla','diane','donna','fannie','diane kelly','donna muraski','dana','erin and irene',
    'erin and kelly','elizabeth','ellen','julia','kathy','lauren','lynn','marie','megan',
    'hannah','jada','julie','katy','laurie','linda','jessica','jo','keena gifford','madge',
    'irene','jessica alba','jo bennett','joan','kelly and erin','gwenneth','helen',
    'isabel','justine','kendall','marcy','helene','isabelle','lily','margaret','meemaw',
    'melissa','mrs. wallace','paris','miss trudy','pam and kelly','penny','molly',
    'nellie and pam','patty','mikela','mrs. davis','nana','rachel','sherri','second cindy',
    'shirley','susan','rose','stephanie','val'
)