friends_m_chars <- c('alan','allesandro','arthur','ben','bill','bobby',
                     'boys','barry','benjamin','billy','billy crystal',
                     'bob','burt','casey','chandler and joey','chase lassiter',
                     'chip','chan','chandler and ross','cliff','carl','chandler',
                     'chandlers','charlton heston','david','dick clark',
                     'donny osmond','dr. burke','dan','danny','dennis phillips',
                     'dirk','don','doug','dr. drake ramoray','dave','devon',
                     'donny','dr green',' dr. drake remoray','dr. green',
                     'dr. stryker remoray','dr. timothy burke','dream joey',
                     'drew','duncan','earl','eddie','eric','ernie','fat joey',
                     'fbob','frank jr.','frank','frank sr.','fredrick','fun bobby',
                     'gary','gavin','gary collins','gene','gunter','gunther',
                     'guru saj','guys','jim','joey and ross','josh','jack','jake',
                     'jason','joey','joey on tv','joshua','issac','joey and chandler',
                     'julio','ken','kyle lowder','kevin','liam','kyle','larry','lipson',
                     'lowell','marc','matthew ashford','mark','matress king','mike',
                     'mr zelner','mr. bowmont','mr. douglas','mr. greene','mr. oberlau',
                     'mr. thompson','mr. waltham','mr.heckles','mr campbell',
                     'mr. boyle','mr. franklin','mr. heckles','mr. posner','mr. treeger',
                     'mr. wineburg','mr zellner','mr. bing','mr. kaplan','mr. simon',
                     'mr. tribbiani','mr. zelner','paulo','peter','paul','owen',
                     'paolo','patrick','pete','phil','ray','raymond','rick','robbie',
                     'robin williams','ross','ross and chandler','scott','robert','roger',
                     'ross ','ross and will','russ','ryan','sebastian','richard','rob',
                     'ross and joey','roy','russell','sid','sergei','stanley','steve',
                     'stu','terry','tommy','wayne','tony','van damme','tim','tom',
                     'uncle dan','vince','will','young ethan','young ross','zack')

seinfeld_m_chars <- c('alec','alton','arnie','artie','al roker','antonio','aaron',
                      'adam','alan','alex trebek','ben','blaine','bobby','barry',
                      'bill','brody','babu bhatt','billy','bob','brett','bruce',
                      'carl','charles','clayton','cedric','charlie','carreras',
                      'craig.','dan','danny tartabull','dennis','dick','donald',
                      'craig','darren','davis','craig ','darryl','duncan',
                      'earl','eric','father jessup','frank','ed','ethan','father curtis',
                      'eddie','enzo','farkus','frank','fred','frank ','fred savage',
                      'gavin','geoge','george ','george wendt','greg','hal','gary',
                      'geoprge','george and jerry','georgge','geroge','gino','goerge',
                      'george','glenn','guillermo','harold','herb','jake','jay',
                      'henry','ian','isaac','jack','jake ','james','jerry',
                      'jerry and george','jerry and newman','jery','jim','joe','joe mayo',
                      'john','jerry ','jerry and joel','jimmy','joe devola','joel',
                      'john tyler','keith','ken','jerry and kramer','jimmy',
                      'joe divola','oey','julio','karl','kevin','kramer','krmaer',
                      'kramer ','kramert','krame','kramer and mickey','kurt','larry',
                      'leo','lloyd','lou','lyle','lloyd ','manny','marcelino','malcolm',
                      'martin','mike','marty','michael','morty','mario','mark','matthew',
                      'mickey','mr elinoff','mr oh','mr ross','mr yamaguchi','mr. arm',
                      'mr. cross','mr. goldstein','mr. green','mr. lippman ','mr. pless',
                      'mr. steinbrenner','mr. thomassoulo','mr lippman','mr peterman',
                      'mr star','mr. . steinbrenner','mr. bevilacqua','mr. cushman',
                      'mr. graham','mr. kruger','mr. morgan','mr. ross','mr. steinbrenner ',
                      'mr. visaki','mr burns','mr lippman','mr tanaka','mr. abbott',
                      'mr. cohen','mr. elinoff','mr. lppman','mr. pitt','mr. s',
                      'mr.lippman ','ned','nemwan','newman ','newman and kramer','nick',
                      'neil','newman','noel','perry','phil','puddy','paul','pete',
                      'petermen','peter','pitt','ramon','ray','regis ','richie','ricky',
                      'roger','raymond','rick','ron','russell','russel','ralph',
                      'remy','ricardi','rickey','robert','ron ','roy','scott',
                      'sid','spike','stan','seth','simon','steinbrenner','soup nazi',
                      'steven','steve','stu','stu ','teddy','the drake','thomassoulo',
                      'todd ','tony','uncle leo ','vic','vincent','timmy','toby',
                      'tim','todd','tom','uncle leo','willie','wilhem','zeke',
                      'willie sr','wilhelm','wilton','zach')

scrubs_m_chars <- c('ben','chuck','crispin','dad','dave','doug','ed','benjamin','brian',
                    'charlie','david','dr. cox','butchie','cox','dan','dennis','billy',
                    'bruce','craig','devin','dr. kelso','billy dee williams','carrot top',
                    'bryan','darryl','eric','glen','harvey','james','jason','jerry','erik estrada',
                    'frank','gary busey','j.d','josh','kelso','larry','leonard','fat frank','franklin',
                    'herbert','j.d.','jack','jeff','kenny','louie anderson','franklyn','hector','hermann',
                    'janitor','jimmie walker','laddy','lyle','jake','jared','jimmy','keith',
                    'mark',"mr. bober", "mr. bober ", "mr. bolger", "mr. booker", "mr. borland",
                    "mr. bradford", "mr. bragen", "mr. brooks", "mr. bursick", "mr. bursky",
                    "mr. burton", "mr. catay", "mr. chambers", "mr. clark", "mr. coleman",
                    "mr. corman", "mr. daniels", "mr. dorian", "mr. foster", "mr. freed",
                    "mr. graff", "mr. hilliard", "mr. hoffner", "mr. hogan", "mr. hovey",
                    "mr. iverson", "mr. james", "mr. jenkins", "mr. keck", "mr. larkin",
                    "mr. marks", "mr. mcnair", "mr. milligan", "mr. moran", "mr. morgan",
                    "mr. morrison", "mr. mueller", "mr. peele", "mr. peeps", "mr. peters",
                    "mr. phillips", "mr. porter", "mr. quinn", "mr. roman", "mr. russell",
                    "mr. silka", "mr. simms", "mr. simon", "mr. sloane", "mr. sommers",
                    "mr. strauss", "mr. summers", "mr. sutton", "mr. taylor", "mr. wilder",
                    "mr. winston", "mr. woodbury", "mr. yeager", "mr. zerbo",
                    'pedro','ricky morgan','roy','ted','todd','tyler','nick','pete','randall',
                    'sean','ted the lawyer','troy','philip','reuben','roland','tom','turk',
                    'randy','reverend turk','ron','scott','tommy','paul','rex','steve','will',
                    'young j.d.','young turk')

frasier_m_chars <- c(' mr. grant','aaron','albert','alistair','andy','ben','bill',' mr. michaels','allen','artie',
                     'billy','alfred','blaine','barry','blake','al','andrew','bob','chris','daniel','brad','carl',
                     'cliff','clark','clifford','danny','dave','carlos','cecil','chuck','clint','craig','david',
                     'brian','bruce','chet','clive','dennis','derek','donald','dwayne','eduardo','esteban',
                     'frank','fuller','gary','gerard','dirk','drake','ed','edward','fraiser','franklin','fred',
                     'gabe','gaston','greg','donny','eddie','eric','ethan','frasier','freddie','freddy','george',
                     'gil','glenn','graham','don','doug','duke','ernie','frederick','frssier','garth','grant',
                     'ian','jerry','jimmy','joey','karl','larry','harry','herm','jake','john','kenny','lawrence',
                     'hank','james','jason','johnny','kevin','hans','jeff','jeremy','jonathan','lance',
                     'harvey','jack','jerome','jimbo','joe','justin','keith','kit','leland','leo','maurice',
                     'mike','noel','leon','luke','marcel','ned','leonard','louis','marco','mark','martin',
                     'neil','nigel','mac','matt','mitch','norman','lucius','mario','michael','niles','preston',
                     'old niles','other niles','petyr','ralph','reggie','rich','rodney','paul','percy','phil',
                     'randy','richard','rob','roger','pete','phillip','robert','roland','ryan','patrick','peter',
                     'rick','rocco','ronald','sebastian','sid','stephen','sully','tom','simon','stan','terrence',
                     'tim','tony','spencer','stefano','ted','thomas','todd','steve','stu','teddy','thad','trent',
                     'sean','steven','trevor','virgil','warren','william','vladimir','wayne','walt','zach',
                     'vinnie','walter','winston','young frasier','woody','young niles')

marriedwc_m_chars <- c('aaron','al sr.','bob','butch','charlie','chris','bob r','bruce','al','bobby','buck','carl',
                       'arnold','barney','biff','bud','charle','bart','bill','brian','carlos','charli','eli',
                       'corky','dave','delbert','doug','eugene','frank','gilbert ironside','e.j.','ephraim','franklin',
                       'dan','dean','ed','ernest','franklin i','furman','gerry','edd','freddy','gary','gilbert',
                       'harry','jeffsn','jim jr','joey','lenny','hiram','irwin','jefrsn','jerfsn','jimbo','johnson',
                       'lance','leo','jeff','jfrsn','jimy','jorge','louie','griff','hal','jack','jay','jeffers','jefrsn',
                       'lewis','hank','harold','ike','jeffrsn','jefsn','jim','joe','lee','mac','mr.s','murphy','myron',
                       'mark','mike','mr. ron','oliver','luke','mikey','mr. w','norman','omar','paul','milton','mr.hugo',
                       'norris','mr.pond','mr tot','nick','otto','ralph','rick','roy','russ','scott','stan','sven','tim p',
                       'tony','teddy','sean','roger','stevev','terry','rolan','ruben','steve','tom','vince','vinni','wally','vinnie')

wg_m_chars <- c(' peter','alan','anton','ben','bj','brian','burt',' will','adam',
                'burton','campbell','andrew','barry','brent','byron','aaron','al roker',
                'andy','anthony','barry karas','bertram','bill','bob','bret',
                'charlie','chuck','colin','dan','danny','desmond','carl','clive','dave',
                'dennis','don','edward','elias','clark','curt','dale','daniel','derek',
                'carlo','chris','clayton','craig','curtis','dalton','ethan','gary','gerald',
                'glenn','jack','elton','gavin','gordon','harry','ian','george','gabe',
                'fernando','george takei','hank','ira','jakc','james','jason','jerry',
                'john','kevin bacon','kurt','leonard','jay','jim','justin','kirk',
                'larry','lenny','linus','jimmy','joe','joseph','julius','ken','lionel',
                'josh','jurgen','kaplan','kevin','lawrence','leo','malcolm','marc',
                'mark','mr zamir','ned','mark juliano','matt','mike','mr. munitz',
                'neil','nick','mario','matt lauer','milo','mitchell','mr. pressman',
                'nathan','lyle','martin','matthew','michael','mr. zamir','nicholas',
                'norman','phil','ralph','robert','russell','officer bob','randall',
                'richard','robert palmer','officer kirk','paul','peter','rob','scott',
                'owen','petersen','rip','roger','ruben','rufus','sebastian','terry',
                'tim','tom','ted','wayne','sid','smitty','stuart','ted farmer','thomas',
                'todd','tom jones','travis','vince','walter','wendell','steve',
                'tommy','vince and vince','warren','will','zack')

office_m_chars <- c('aaron rodgers','andy','bert','aj','alonzo','ben','a.j.',
                    'abe','alan','ben franklin','brian','calvin','cameron',
                    'casey dean','charles','cherokee jack','bob','brandon',
                    'captain jack','chet','christian','bill','billy','bob vance',
                    'bruce','christian slater','clark','clay aiken','creed','dacvid wallace',
                    'dan','darry','daryl','david wallace','dennis','colin','craig',
                    'dan gore','danny','darryl','david','david wallcve','deangelo',
                    'curtis','dacvid walalce','dale','darrly','david brent','deagnelo',
                    'denagelo','devon','dight','dwight ','dwightkschrute','eric',
                    'evan','fred','ed','ernesto','fake jim','fred henry','gabe',
                    'doug','dwight','dwight.','fake stanley','frank','glen',
                    'harry','ira','gideon','glenn','hank','harvey','hunter','gil',
                    'henry','isaac','jerome bettis','justin','kenny','leo','luke',
                    'jake','jerry','jim','josh','julius','kevin','larry myers',
                    'lester','jakey','jim ','jim9334','m ichael','malcolm','mark mcgrath',
                    'michae','micheal','miichael','martin','merv','micael','michael',
                    'michel','mark','matt','merv bronte','micahel','michael ','michal',
                    'mihael','mr. brown','mr. ramish','mr. schofield','mr. figaro',
                    'mr. romanko','nick','oscar','packer','mr. beesly','mr. halpert',
                    'mr. ruger','nate','paul','phil','phillip','ravi','paul faust','pete',
                    'phil maguire','rafe','pete halpert','philip','randy','robert dunder',
                    'rolando','roy','ryan','samuel','robert','rolf','rory','ryan howard',
                    'senator lipton','sensei ira','shane','stanely','robert california',
                    'roger','rolph','stanley','steve','teddy','todd packer','vikram',
                    'stu','teddy wallace','toby','tom halpert','trevor','ty','wally amos',
                    'ted','todd','tom','tony','troy','uncle al','walt jr.','walter',
                    'warren','zeke','walter jr','warehouse michael','young michael')